version: "3.2"
services:
 py-mongo:
  build: ${PWD}
  volumes:
   - ${PWD}/mongo-data:/data/db
   - ${PWD}/mongo-app:/usr/src/app
  ports:
   - "27017:27017"
  environment:
   - MONGO_INITDB_ROOT_USERNAME=root
   - MONGO_INITDB_ROOT_PASSWORD=1234